mkdir pdbFiles
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save /pdbFiles/5con.pdb, 5con
save /pdbFiles/5coo.pdb, 5coo
save /pdbFiles/5cop.pdb, 5cop
save /pdbFiles/4hla.pdb, 4hla
save /pdbFiles/5bry.pdb, 5bry
save /pdbFiles/5bs4.pdb, 5bs4
save /pdbFiles/4hdp.pdb, 4hdp
save /pdbFiles/5dgw,.pdb, 5dgw,
save /pdbFiles/3cyw.pdb, 3cyw
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save /pdbFiles/5con.pdb, 5con
save /pdbFiles/5coo.pdb, 5coo
save /pdbFiles/5cop.pdb, 5cop
save /pdbFiles/4hla.pdb, 4hla
save /pdbFiles/5bry.pdb, 5bry
save /pdbFiles/5bs4.pdb, 5bs4
save /pdbFiles/4hdp.pdb, 4hdp
save /pdbFiles/5dgw,.pdb, 5dgw,
save /pdbFiles/3cyw.pdb, 3cyw
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save /pdbFiles/5con.pdb, 5con
save /pdbFiles/5coo.pdb, 5coo
save /pdbFiles/5cop.pdb, 5cop
save /pdbFiles/4hla.pdb, 4hla
save /pdbFiles/5bry.pdb, 5bry
save /pdbFiles/5bs4.pdb, 5bs4
save /pdbFiles/4hdp.pdb, 4hdp
save /pdbFiles/5dgw,.pdb, 5dgw,
save /pdbFiles/3cyw.pdb, 3cyw
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save /pdbFiles/5con.pdb, 5con
save /pdbFiles/5coo.pdb, 5coo
save /pdbFiles/5cop.pdb, 5cop
save /pdbFiles/4hla.pdb, 4hla
save /pdbFiles/5bry.pdb, 5bry
save /pdbFiles/5bs4.pdb, 5bs4
save /pdbFiles/4hdp.pdb, 4hdp
save /pdbFiles/5dgw,.pdb, 5dgw,
save /pdbFiles/3cyw.pdb, 3cyw
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save 5con.pdb, 5con
save 5coo.pdb, 5coo
save 5cop.pdb, 5cop
save 4hla.pdb, 4hla
save 5bry.pdb, 5bry
save 5bs4.pdb, 5bs4
save 4hdp.pdb, 4hdp
save 5dgw,.pdb, 5dgw,
save 3cyw.pdb, 3cyw
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save 5con.pdb, 5con
save 5coo.pdb, 5coo
save 5cop.pdb, 5cop
save 4hla.pdb, 4hla
save 5bry.pdb, 5bry
save 5bs4.pdb, 5bs4
save 4hdp.pdb, 4hdp
save 5dgw,.pdb, 5dgw,
save 3cyw.pdb, 3cyw
fetch 5con, async=0
fetch 5coo, async=0
fetch 5cop, async=0
fetch 4hla, async=0
fetch 5bry, async=0
fetch 5bs4, async=0
fetch 4hdp, async=0
fetch 5dgw,, async=0
fetch 3cyw, async=0
save 5con.pdb, 5con
save 5coo.pdb, 5coo
save 5cop.pdb, 5cop
save 4hla.pdb, 4hla
save 5bry.pdb, 5bry
save 5bs4.pdb, 5bs4
save 4hdp.pdb, 4hdp
save 5dgw,.pdb, 5dgw,
save 3cyw.pdb, 3cyw
